// This file contains the main logic for the browser's main window.
// It handles UI interactions, navigation, tab management, and integration with WebView2.

using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.Wpf;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.IO;
using System.Text.Json;
using System.Speech.Synthesis;
using System.Windows.Media.Imaging;
using System.Windows.Media;
using System.Diagnostics;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Windows.Interop;
using System.Runtime.InteropServices;
using System.Net.NetworkInformation;
using System.Timers;

// Ensure these 'using' directives are present for the auxiliary classes
using NavegadorWeb.Classes; // For TabItemData, TabGroup, TabGroupManager, CapturedPageData, RelayCommand, TabGroupState, ToolbarPosition
using NavegadorWeb.Extensions; // For CustomExtension, ExtensionManager


namespace NavegadorWeb
{
    // The partial MainWindow class is already generated by the compiler to include XAML elements.
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        // Configuration keys for application settings
        private const string HomePageSettingKey = "DefaultHomePage";
        private const string AdBlockerSettingKey = "AdBlockerEnabled";
        private const string DefaultSearchEngineSettingKey = "DefaultSearchEngine";
        private const string TabSuspensionSettingKey = "TabSuspensionEnabled";
        private const string RestoreSessionSettingKey = "RestoreSessionOnStartup";
        private const string LastSessionUrlsSettingKey = "LastSessionUrls";
        private const string LastSessionTabGroupsSettingKey = "LastSessionTabGroups";
        private const string LastSelectedTabGroupSettingKey = "LastSelectedTabGroup";

        // Private fields for application state
        private string _defaultHomePage = "https://www.google.com";
        private bool _isAdBlockerEnabled;
        private bool _isGeminiModeActive;
        private bool _isFindBarVisible;
        private string _findSearchText = "";
        private string _findResultsText = "";
        private TabItemData? _selectedTabItem;
        private double _downloadProgress;
        private Visibility _downloadProgressBarVisibility = Visibility.Collapsed;
        private SpeechSynthesizer? _speechSynthesizer;
        private bool _isReadingAloud = false;
        private System.Timers.Timer _tabSuspensionTimer;
        private TimeSpan _tabSuspensionDelay = TimeSpan.FromMinutes(5);
        private bool _isTabSuspensionEnabled;

        // Public properties with change notification (INotifyPropertyChanged)
        public bool IsAdBlockerEnabled
        {
            get => _isAdBlockerEnabled;
            set
            {
                if (_isAdBlockerEnabled != value)
                {
                    _isAdBlockerEnabled = value;
                    OnPropertyChanged(nameof(IsAdBlockerEnabled));
                    ApplyAdBlockerSettings(); // Apply ad blocker settings when changed
                }
            }
        }

        public bool IsGeminiModeActive
        {
            get => _isGeminiModeActive;
            set
            {
                if (_isGeminiModeActive != value)
                {
                    _isGeminiModeActive = value;
                    OnPropertyChanged(nameof(IsGeminiModeActive));
                    ApplyTheme(); // Apply theme changes when Gemini mode is toggled
                }
            }
        }

        public bool IsFindBarVisible
        {
            get => _isFindBarVisible;
            set
            {
                if (_isFindBarVisible != value)
                {
                    _isFindBarVisible = value;
                    OnPropertyChanged(nameof(IsFindBarVisible));
                }
            }
        }

        public string FindSearchText
        {
            get => _findSearchText;
            set
            {
                if (_findSearchText != value)
                {
                    _findSearchText = value;
                    OnPropertyChanged(nameof(FindSearchText));
                    FindInPage(_findSearchText); // Perform search when text changes
                }
            }
        }

        public string FindResultsText
        {
            get => _findResultsText;
            set
            {
                if (_findResultsText != value)
                {
                    _findResultsText = value;
                    OnPropertyChanged(nameof(FindResultsText));
                }
            }
        }

        public TabItemData? SelectedTabItem
        {
            get => _selectedTabItem;
            set
            {
                if (_selectedTabItem != value)
                {
                    _selectedTabItem = value;
                    OnPropertyChanged(nameof(SelectedTabItem));
                    UpdateBrowserControls(); // Update UI controls based on selected tab
                }
            }
        }

        public double DownloadProgress
        {
            get => _downloadProgress;
            set
            {
                _downloadProgress = value;
                OnPropertyChanged(nameof(DownloadProgress));
            }
        }

        public Visibility DownloadProgressBarVisibility
        {
            get => _downloadProgressBarVisibility;
            set
            {
                _downloadProgressBarVisibility = value;
                OnPropertyChanged(nameof(DownloadProgressBarVisibility));
            }
        }

        public TabGroupManager TabGroupManager { get; private set; }
        public ExtensionManager ExtensionManager { get; private set; }

        public ObservableCollection<CapturedPageData> CapturedPagesForGemini { get; set; } = new ObservableCollection<CapturedPageData>();

        public bool IsTabSuspensionEnabled
        {
            get => _isTabSuspensionEnabled;
            set
            {
                if (_isTabSuspensionEnabled != value)
                {
                    _isTabSuspensionEnabled = value;
                    OnPropertyChanged(nameof(IsTabSuspensionEnabled));
                    if (_isTabSuspensionEnabled)
                    {
                        StartTabSuspensionTimer();
                    }
                    else
                    {
                        StopTabSuspensionTimer();
                    }
                }
            }
        }

        // Event for property change notification
        public event PropertyChangedEventHandler? PropertyChanged;

        protected void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        // Constants for window sizing
        private const double MIN_WIDTH = 800;
        private const double MIN_HEIGHT = 600;

        // DllImport for window dragging (custom title bar)
        [DllImport("user32.dll")]
        public static extern IntPtr SendMessage(IntPtr hWnd, int wMsg, int wParam, int lParam);
        private const int WM_NCLBUTTONDOWN = 0xA1;
        private const int HT_CAPTION = 0x2;

        public MainWindow()
        {
            InitializeComponent(); // This method is automatically generated by WPF to initialize XAML elements.
            this.DataContext = this; // Set DataContext for data binding

            TabGroupManager = new TabGroupManager();
            ExtensionManager = new ExtensionManager();

            LoadSettings(); // Load application settings
            ApplyAdBlockerSettings(); // Apply ad blocker settings
            ApplyTheme(); // Apply current theme

            // Initialize speech synthesizer for read-aloud functionality
            _speechSynthesizer = new SpeechSynthesizer();
            _speechSynthesizer.SetOutputToDefaultAudioDevice();

            // Setup tab suspension timer
            _tabSuspensionTimer = new System.Timers.Timer(_tabSuspensionDelay.TotalMilliseconds);
            _tabSuspensionTimer.Elapsed += TabSuspensionTimer_Elapsed;
            _tabSuspensionTimer.AutoReset = true;
            if (IsTabSuspensionEnabled)
            {
                StartTabSuspensionTimer();
            }

            // Register for user activity events to reset tab suspension timer
            this.PreviewMouseMove += MainWindow_UserActivity;
            this.PreviewKeyDown += MainWindow_UserActivity;
        }

        // Starts the tab suspension timer
        private void StartTabSuspensionTimer()
        {
            _tabSuspensionTimer.Start();
        }

        // Stops the tab suspension timer
        private void StopTabSuspensionTimer()
        {
            _tabSuspensionTimer.Stop();
        }

        // Resets the tab suspension timer on user activity
        private void MainWindow_UserActivity(object sender, EventArgs e)
        {
            if (IsTabSuspensionEnabled)
            {
                _tabSuspensionTimer.Stop();
                _tabSuspensionTimer.Start();
            }
        }

        // Suspends inactive tabs when the timer elapses
        private async void TabSuspensionTimer_Elapsed(object? sender, ElapsedEventArgs e)
        {
            await Dispatcher.InvokeAsync(async () =>
            {
                foreach (var group in TabGroupManager.TabGroups)
                {
                    foreach (var tab in group.TabsInGroup)
                    {
                        // Suspend tab if it's not the currently selected tab and has a WebView2 instance
                        if (tab != SelectedTabItem && tab.WebViewInstance != null && tab.WebViewInstance.CoreWebView2 != null)
                        {
                            tab.IsSuspended = true;
                            tab.LastSuspendedUrl = tab.WebViewInstance.Source.ToString(); // Save current URL
                            tab.WebViewInstance.CoreWebView2.Stop(); // Stop loading
                            tab.WebViewInstance.Source = new Uri("about:blank"); // Navigate to blank page
                            Console.WriteLine($"Tab suspended: {tab.Title}");
                        }
                    }
                }
            });
        }

        // Activates a suspended tab
        public async void ActivateTab(TabItemData tab)
        {
            if (tab.IsSuspended)
            {
                tab.IsSuspended = false;
                // If the tab was suspended and has a saved URL, navigate back to it
                if (tab.WebViewInstance != null && tab.WebViewInstance.CoreWebView2 != null && !string.IsNullOrEmpty(tab.LastSuspendedUrl))
                {
                    tab.WebViewInstance.Source = new Uri(tab.LastSuspendedUrl);
                    Console.WriteLine($"Tab reactivated: {tab.Title}");
                }
            }
            SelectedTabItem = tab; // Set this tab as the selected one
        }

        // Loads application settings from ConfigurationManager
        private void LoadSettings()
        {
            _defaultHomePage = ConfigurationManager.AppSettings[HomePageSettingKey] ?? "https://www.google.com";
            IsAdBlockerEnabled = bool.Parse(ConfigurationManager.AppSettings[AdBlockerSettingKey] ?? "false");
            IsTabSuspensionEnabled = bool.Parse(ConfigurationManager.AppSettings[TabSuspensionSettingKey] ?? "false");

            // Restore last session if enabled, otherwise open a new tab with default home page
            if (bool.Parse(ConfigurationManager.AppSettings[RestoreSessionSettingKey] ?? "false"))
            {
                RestoreLastSession();
            }
            else
            {
                AddNewTab(_defaultHomePage);
            }
        }

        // Saves application settings to ConfigurationManager
        private void SaveSettings()
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            config.AppSettings.Settings[HomePageSettingKey].Value = _defaultHomePage;
            config.AppSettings.Settings[AdBlockerSettingKey].Value = IsAdBlockerEnabled.ToString();
            config.AppSettings.Settings[TabSuspensionSettingKey].Value = IsTabSuspensionEnabled.ToString();

            // Save current session if restore on startup is enabled, otherwise clear session data
            if (bool.Parse(ConfigurationManager.AppSettings[RestoreSessionSettingKey] ?? "false"))
            {
                SaveCurrentSession();
            }
            else
            {
                config.AppSettings.Settings[LastSessionUrlsSettingKey].Value = "";
                config.AppSettings.Settings[LastSessionTabGroupsSettingKey].Value = "";
                config.AppSettings.Settings[LastSelectedTabGroupSettingKey].Value = "";
            }

            config.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("appSettings");
        }

        // Saves the URLs of all open tabs and tab groups to settings
        private void SaveCurrentSession()
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);

            // Serialize all tab URLs
            var allUrls = TabGroupManager.TabGroups
                                        .SelectMany(g => g.TabsInGroup)
                                        .Select(tab => tab.WebViewInstance?.Source?.ToString())
                                        .Where(url => !string.IsNullOrEmpty(url) && url != "about:blank")
                                        .ToList();
            config.AppSettings.Settings[LastSessionUrlsSettingKey].Value = JsonSerializer.Serialize(allUrls);

            // Serialize tab group states (group ID, name, tab URLs, selected tab URL)
            var groupStates = TabGroupManager.TabGroups.Select(g => new TabGroupState
            {
                GroupId = g.GroupId,
                GroupName = g.GroupName,
                TabUrls = g.TabsInGroup.Select(t => t.WebViewInstance?.Source?.ToString()).Where(url => !string.IsNullOrEmpty(url) && url != "about:blank").ToList(),
                SelectedTabUrl = g.SelectedTabItem?.WebViewInstance?.Source?.ToString()
            }).ToList();
            config.AppSettings.Settings[LastSessionTabGroupsSettingKey].Value = JsonSerializer.Serialize(groupStates);

            // Save the ID of the currently selected tab group
            config.AppSettings.Settings[LastSelectedTabGroupSettingKey].Value = TabGroupManager.SelectedTabGroup?.GroupId ?? "";

            config.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("appSettings");
        }

        // Restores the last browsing session from settings
        private async void RestoreLastSession()
        {
            var savedTabGroupsJson = ConfigurationManager.AppSettings[LastSessionTabGroupsSettingKey];
            if (!string.IsNullOrEmpty(savedTabGroupsJson))
            {
                try
                {
                    var groupStates = JsonSerializer.Deserialize<List<TabGroupState>>(savedTabGroupsJson);
                    if (groupStates != null && groupStates.Any())
                    {
                        TabGroupManager.TabGroups.Clear(); // Clear existing default tab

                        foreach (var groupState in groupStates)
                        {
                            var newGroup = new TabGroup(groupState.GroupId, groupState.GroupName);
                            TabGroupManager.AddGroup(newGroup);

                            foreach (var url in groupState.TabUrls)
                            {
                                if (!string.IsNullOrEmpty(url))
                                {
                                    var newTab = CreateNewTabItem(url);
                                    newGroup.AddTab(newTab);
                                    // Ensure CoreWebView2 is initialized for each restored tab
                                    await newTab.WebViewInstance.EnsureCoreWebView2Async(null);
                                }
                            }

                            if (!string.IsNullOrEmpty(groupState.SelectedTabUrl))
                            {
                                var selectedTab = newGroup.TabsInGroup.FirstOrDefault(t => t.WebViewInstance?.Source?.ToString() == groupState.SelectedTabUrl);
                                if (selectedTab != null)
                                {
                                    newGroup.SelectedTabItem = selectedTab;
                                }
                            }
                        }

                        // Restore the last selected tab group
                        var lastSelectedGroupId = ConfigurationManager.AppSettings[LastSelectedTabGroupSettingKey];
                        var restoredSelectedGroup = TabGroupManager.TabGroups.FirstOrDefault(g => g.GroupId == lastSelectedGroupId);
                        if (restoredSelectedGroup != null)
                        {
                            TabGroupManager.SelectedTabGroup = restoredSelectedGroup;
                            BrowserTabs.ItemsSource = restoredSelectedGroup.TabsInGroup;
                            SelectedTabItem = restoredSelectedGroup.SelectedTabItem;
                        }
                        else
                        {
                            // Fallback to default group if the last selected group is not found
                            TabGroupManager.SelectedTabGroup = TabGroupManager.GetDefaultGroup();
                            BrowserTabs.ItemsSource = TabGroupManager.GetDefaultGroup().TabsInGroup;
                            SelectedTabItem = TabGroupManager.GetDefaultGroup().TabsInGroup.FirstOrDefault();
                        }
                    }
                    else
                    {
                        AddNewTab(_defaultHomePage); // If no saved session, open default home page
                    }
                }
                catch (JsonException ex)
                {
                    MessageBox.Show($"Error restoring session: {ex.Message}", "Restoration Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    AddNewTab(_defaultHomePage); // On error, open default home page
                }
            }
            else
            {
                AddNewTab(_defaultHomePage); // If no saved session data, open default home page
            }
        }

        // Applies ad blocker settings to all WebView2 instances
        private void ApplyAdBlockerSettings()
        {
            foreach (var group in TabGroupManager.TabGroups)
            {
                foreach (var tab in group.TabsInGroup)
                {
                    if (tab.WebViewInstance != null && tab.WebViewInstance.CoreWebView2 != null)
                    {
                        if (IsAdBlockerEnabled)
                        {
                            // Set web resource context filter to block certain content types
                            tab.WebViewInstance.CoreWebView2.SetWebResourceContextFilter(
                                CoreWebView2WebResourceContext.Image, CoreWebView2WebResourceContext.Script,
                                CoreWebView2WebResourceContext.Stylesheet, CoreWebView2WebResourceContext.Media,
                                CoreWebView2WebResourceContext.Font);
                        }
                        else
                        {
                            // Clear the filter if ad blocker is disabled
                            tab.WebViewInstance.CoreWebView2.ClearWebResourceContextFilter();
                        }
                    }
                }
            }
        }

        // Applies the current theme (default or Gemini mode)
        private void ApplyTheme()
        {
            // Remove existing dynamic resources
            Resources.Remove("BrowserBackgroundColor");
            Resources.Remove("BrowserBackgroundBrush");
            Resources.Remove("BrowserForegroundColor");
            Resources.Remove("BrowserForegroundBrush");

            // Add new dynamic resources based on Gemini mode status
            if (IsGeminiModeActive)
            {
                Resources.Add("BrowserBackgroundColor", (Color)FindResource("GeminiBackgroundColor"));
                Resources.Add("BrowserBackgroundBrush", (SolidColorBrush)FindResource("GeminiBackgroundBrush"));
                Resources.Add("BrowserForegroundColor", (Color)FindResource("GeminiForegroundColor"));
                Resources.Add("BrowserForegroundBrush", (SolidColorBrush)FindResource("GeminiForegroundBrush"));
            }
            else
            {
                Resources.Add("BrowserBackgroundColor", (Color)FindResource("DefaultBrowserBackgroundColor"));
                Resources.Add("BrowserBackgroundBrush", (SolidColorBrush)FindResource("DefaultBrowserBackgroundBrush"));
                Resources.Add("BrowserForegroundColor", (Color)FindResource("DefaultBrowserForegroundColor"));
                Resources.Add("BrowserForegroundBrush", (SolidColorBrush)FindResource("DefaultBrowserForegroundBrush"));
            }
            // Update the main window's background
            MainBorder.Background = (SolidColorBrush)Resources["BrowserBackgroundBrush"];
        }

        // Event handler for window loaded event
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            // Restore window size and position from settings if not maximized
            if (Application.Current.MainWindow != null &&
                (Application.Current.MainWindow.WindowState == WindowState.Maximized ||
                 (Application.Current.MainWindow.ActualWidth == SystemParameters.WorkArea.Width &&
                  Application.Current.MainWindow.ActualHeight == SystemParameters.WorkArea.Height)))
            {
                this.WindowState = WindowState.Maximized;
            }
            else
            {
                if (double.TryParse(ConfigurationManager.AppSettings["WindowWidth"], out double width))
                {
                    this.Width = Math.Max(width, MIN_WIDTH);
                }
                if (double.TryParse(ConfigurationManager.AppSettings["WindowHeight"], out double height))
                {
                    this.Height = Math.Max(height, MIN_HEIGHT);
                }
                if (double.TryParse(ConfigurationManager.AppSettings["WindowLeft"], out double left))
                {
                    this.Left = left;
                }
                if (double.TryParse(ConfigurationManager.AppSettings["WindowTop"], out double top))
                {
                    this.Top = top;
                }
            }

            // Set TabControl's ItemsSource and selected item
            BrowserTabs.ItemsSource = TabGroupManager.GetDefaultGroup().TabsInGroup;
            SelectedTabItem = TabGroupManager.GetDefaultGroup().TabsInGroup.FirstOrDefault();

            // Apply TabHeaderTemplate
            BrowserTabs.ItemTemplate = (DataTemplate)this.Resources["TabHeaderTemplate"];

            // Register WebView2 events for all existing tabs
            foreach (var group in TabGroupManager.TabGroups)
            {
                foreach (var tab in group.TabsInGroup)
                {
                    tab.WebViewInstance.SourceChanged += WebView_SourceChanged;
                    tab.WebViewInstance.NavigationCompleted += WebView_NavigationCompleted;
                    tab.WebViewInstance.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
                    tab.WebViewInstance.WebMessageReceived += WebView_WebMessageReceived;
                    tab.WebViewInstance.DownloadStarting += WebView_DownloadStarting;
                }
            }

            // Load and display extensions
            ExtensionManager.LoadExtensions();
            ExtensionsMenuItem.DataContext = ExtensionManager;
        }

        // Event handler for window closing event
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            // Save window size and position before closing
            if (this.WindowState == WindowState.Maximized)
            {
                config.AppSettings.Settings["WindowWidth"].Value = this.RestoreBounds.Width.ToString();
                config.AppSettings.Settings["WindowHeight"].Value = this.RestoreBounds.Height.ToString();
                config.AppSettings.Settings["WindowLeft"].Value = this.RestoreBounds.Left.ToString();
                config.AppSettings.Settings["WindowTop"].Value = this.RestoreBounds.Top.ToString();
            }
            else
            {
                config.AppSettings.Settings["WindowWidth"].Value = this.Width.ToString();
                config.AppSettings.Settings["WindowHeight"].Value = this.Height.ToString();
                config.AppSettings.Settings["WindowLeft"].Value = this.Left.ToString();
                config.AppSettings.Settings["WindowTop"].Value = this.Top.ToString();
            }
            config.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("appSettings");

            SaveSettings(); // Save application settings and session

            _speechSynthesizer?.Dispose(); // Dispose speech synthesizer
            _tabSuspensionTimer?.Stop(); // Stop tab suspension timer
            _tabSuspensionTimer?.Dispose(); // Dispose tab suspension timer

            // Dispose all WebView2 instances to release resources
            foreach (var group in TabGroupManager.TabGroups)
            {
                foreach (var tab in group.TabsInGroup)
                {
                    tab.WebViewInstance?.Dispose();
                }
            }
        }

        // Event handler for window state changed (e.g., maximized/normal)
        private void MainWindow_StateChanged(object? sender, EventArgs e)
        {
            // Adjust border thickness and corner radius when window state changes
            if (WindowState == WindowState.Maximized)
            {
                MainBorder.BorderThickness = new Thickness(0);
                MainBorder.CornerRadius = new CornerRadius(0);
            }
            else
            {
                MainBorder.BorderThickness = new Thickness(1);
                MainBorder.CornerRadius = new CornerRadius(10);
            }
        }

        // Event handler for custom title bar dragging
        private void Window_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ChangedButton == MouseButton.Left)
            {
                this.DragMove(); // Allow dragging the window
            }
        }

        // Event handler for minimize button click
        private void MinimizeButton_Click(object sender, RoutedEventArgs e)
        {
            this.WindowState = WindowState.Minimized;
        }

        // Event handler for maximize/restore button click
        private void MaximizeRestoreButton_Click(object sender, RoutedEventArgs e)
        {
            if (this.WindowState == WindowState.Maximized)
            {
                this.WindowState = WindowState.Normal;
            }
            else
            {
                this.WindowState = WindowState.Maximized;
            }
        }

        // Event handler for close button click
        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        // Creates a new TabItemData instance with a WebView2
        private TabItemData CreateNewTabItem(string url)
        {
            var webView = new WebView2();
            var newTabItem = new TabItemData(webView)
            {
                Title = "Loading...",
                Url = url,
                CapturedData = new CapturedPageData { Url = url }
            };

            webView.Source = new Uri(url);
            // Register WebView2 events for the new tab
            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
            webView.NavigationCompleted += WebView_NavigationCompleted;
            webView.SourceChanged += WebView_SourceChanged;
            webView.WebMessageReceived += WebView_WebMessageReceived;
            webView.DownloadStarting += WebView_DownloadStarting;
            webView.ContextMenuOpening += WebView_ContextMenuOpening;

            // Apply custom scrollbar style to WebView2
            webView.Loaded += (s, e) =>
            {
                var border = VisualTreeHelper.GetChild(webView, 0) as Border;
                if (border != null)
                {
                    var scrollViewer = border.Child as ScrollViewer;
                    if (scrollViewer != null)
                    {
                        scrollViewer.ScrollBarStyle = (Style)FindResource("CustomScrollBarStyle");
                    }
                }
            };

            return newTabItem;
        }

        // Adds a new tab to the default tab group
        private void AddNewTab(string url = "about:blank")
        {
            TabItemData newTabItem = CreateNewTabItem(url);
            TabGroupManager.GetDefaultGroup().AddTab(newTabItem);
            SelectedTabItem = newTabItem; // Select the newly added tab
        }

        // Event handler for adding a new tab via button click
        private void AddNewTabButton_Click(object sender, RoutedEventArgs e)
        {
            AddNewTab(_defaultHomePage);
        }

        // Event handler for closing a tab via button click
        private void CloseTabButton_Click(object sender, RoutedEventArgs e)
        {
            if (sender is Button button && button.Tag is TabItemData tabToClose)
            {
                var currentGroup = TabGroupManager.GetGroupByTab(tabToClose);
                if (currentGroup != null)
                {
                    currentGroup.RemoveTab(tabToClose); // Remove tab from its group
                    tabToClose.WebViewInstance?.Dispose(); // Dispose WebView2 instance

                    // If the group becomes empty and it's not the last group, remove the group
                    if (currentGroup.TabsInGroup.Count == 0 && TabGroupManager.TabGroups.Count > 1)
                    {
                        TabGroupManager.RemoveGroup(currentGroup);
                    }

                    // If all tab groups are empty, open a new default tab
                    if (TabGroupManager.TabGroups.All(g => g.TabsInGroup.Count == 0))
                    {
                        AddNewTab(_defaultHomePage);
                    }
                    // If the closed tab was selected, select another tab in the same group or the first tab of the first group
                    else if (SelectedTabItem == tabToClose && currentGroup.TabsInGroup.Any())
                    {
                        SelectedTabItem = currentGroup.TabsInGroup.FirstOrDefault();
                    }
                    else if (SelectedTabItem == tabToClose && TabGroupManager.TabGroups.Any())
                    {
                        SelectedTabItem = TabGroupManager.TabGroups.First().TabsInGroup.FirstOrDefault();
                        BrowserTabs.ItemsSource = TabGroupManager.SelectedTabGroup?.TabsInGroup;
                    }
                }
            }
        }

        // CanExecute handler for GoBack command
        private void GoBackCommand_CanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = SelectedTabItem != null && SelectedTabItem.WebViewInstance.CanGoBack;
        }

        // Executed handler for GoBack command
        private void GoBackCommand_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            SelectedTabItem?.WebViewInstance?.GoBack();
        }

        // CanExecute handler for GoForward command
        private void GoForwardCommand_CanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = SelectedTabItem != null && SelectedTabItem.WebViewInstance.CanGoForward;
        }

        // Executed handler for GoForward command
        private void GoForwardCommand_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            SelectedTabItem?.WebViewInstance?.GoForward();
        }

        // CanExecute handler for Refresh command
        private void RefreshCommand_CanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = SelectedTabItem != null;
        }

        // Executed handler for Refresh command
        private void RefreshCommand_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            SelectedTabItem?.WebViewInstance?.Reload();
        }

        // CanExecute handler for Home command
        private void HomeCommand_CanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        // Executed handler for Home command
        private void HomeCommand_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            NavigateToUrl(_defaultHomePage);
        }

        // CanExecute handler for Search command
        private void SearchCommand_CanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = !string.IsNullOrWhiteSpace(AddressBar.Text);
        }

        // Executed handler for Search command
        private void SearchCommand_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            NavigateToUrl(AddressBar.Text);
        }

        // KeyDown event handler for AddressBar (handles Enter key for navigation)
        private void AddressBar_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter)
            {
                NavigateToUrl(AddressBar.Text);
            }
        }

        // Click event handler for navigation button
        private void NavigateButton_Click(object sender, RoutedEventArgs e)
        {
            NavigateToUrl(AddressBar.Text);
        }

        // Navigates the selected tab to the specified URL
        private void NavigateToUrl(string url)
        {
            if (SelectedTabItem != null && SelectedTabItem.WebViewInstance != null)
            {
                string fullUrl = url;
                // If URL doesn't contain a scheme, try to prepend "https://" or use search engine
                if (!url.Contains("://") && !url.StartsWith("file://") && !url.StartsWith("about:"))
                {
                    if (url.Contains(".")) // Likely a domain
                    {
                        fullUrl = "https://" + url;
                    }
                    else // Likely a search query
                    {
                        string searchEngineUrl = ConfigurationManager.AppSettings[DefaultSearchEngineSettingKey] ?? "https://www.google.com/search?q=";
                        fullUrl = searchEngineUrl + Uri.EscapeDataString(url);
                    }
                }

                try
                {
                    SelectedTabItem.WebViewInstance.Source = new Uri(fullUrl);
                }
                catch (UriFormatException)
                {
                    MessageBox.Show("Invalid URL or search term.", "Navigation Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }

        // Event handler for WebView2 NavigationCompleted event
        private async void WebView_NavigationCompleted(object? sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            var webView = sender as WebView2;
            if (webView != null)
            {
                var tab = TabGroupManager.TabGroups.SelectMany(g => g.TabsInGroup).FirstOrDefault(t => t.WebViewInstance == webView);
                if (tab != null)
                {
                    tab.Url = webView.Source.ToString(); // Update tab URL
                    AddressBar.Text = tab.Url; // Update address bar

                    await UpdateTabTitleAndFavicon(tab, webView); // Update tab title and favicon

                    if (tab.IsReaderMode)
                    {
                        tab.IsReaderMode = false; // Exit reader mode if active after navigation
                    }

                    // Execute text extraction extension if enabled
                    var textExtractionExtension = ExtensionManager.Extensions.FirstOrDefault(ext => ext.Name == "Text Extractor");
                    if (textExtractionExtension != null && textExtractionExtension.IsEnabled)
                    {
                        string scriptContent = textExtractionExtension.LoadScriptContent();
                        if (!string.IsNullOrEmpty(scriptContent))
                        {
                            await webView.CoreWebView2.ExecuteScriptAsync(scriptContent);
                        }
                    }

                    // Execute all other enabled extensions
                    foreach (var extension in ExtensionManager.Extensions)
                    {
                        if (extension.IsEnabled)
                        {
                            string scriptContent = extension.LoadScriptContent();
                            if (!string.IsNullOrEmpty(scriptContent))
                            {
                                await webView.CoreWebView2.ExecuteScriptAsync(scriptContent);
                            }
                        }
                    }
                }
            }
        }

        // Updates the tab's title and favicon
        private async Task UpdateTabTitleAndFavicon(TabItemData tab, WebView2 webView)
        {
            if (webView.CoreWebView2 != null)
            {
                try
                {
                    // Get page title
                    string title = await webView.CoreWebView2.ExecuteScriptAsync("document.title");
                    tab.Title = title.Replace("\"", ""); // Remove quotes from title

                    // Get favicon URL using JavaScript
                    string getFaviconScript = @"
                        (function() {
                            var faviconLink = document.querySelector('link[rel~=""icon""]');
                            if (faviconLink) {
                                return faviconLink.href;
                            }
                            return null;
                        })();
                    ";
                    string faviconUrlJson = await webView.CoreWebView2.ExecuteScriptAsync(getFaviconScript);
                    string faviconUrl = JsonSerializer.Deserialize<string>(faviconUrlJson) ?? "";

                    if (!string.IsNullOrEmpty(faviconUrl))
                    {
                        // Resolve relative favicon URLs
                        if (!faviconUrl.Contains("://"))
                        {
                            Uri baseUri = new Uri(webView.Source.ToString());
                            Uri absoluteUri = new Uri(baseUri, faviconUrl);
                            faviconUrl = absoluteUri.ToString();
                        }

                        try
                        {
                            // Download favicon and convert to BitmapImage
                            using (var httpClient = new System.Net.Http.HttpClient())
                            {
                                byte[] faviconBytes = await httpClient.GetByteArrayAsync(faviconUrl);
                                tab.Favicon = new BitmapImage();
                                tab.Favicon.BeginInit();
                                tab.Favicon.StreamSource = new MemoryStream(faviconBytes);
                                tab.Favicon.EndInit();

                                tab.CapturedData.FaviconBase64 = Convert.ToBase64String(faviconBytes); // Save as Base64 for Gemini
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Error downloading or processing favicon: {ex.Message}");
                            tab.Favicon = null;
                            tab.CapturedData.FaviconBase64 = string.Empty;
                        }
                    }
                    else
                    {
                        tab.Favicon = null;
                        tab.CapturedData.FaviconBase64 = string.Empty;
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error getting title or favicon: {ex.Message}");
                    tab.Title = "Error";
                    tab.Favicon = null;
                    tab.CapturedData.FaviconBase64 = string.Empty;
                }
            }
        }

        // Event handler for WebView2 SourceChanged event
        private void WebView_SourceChanged(object? sender, CoreWebView2SourceChangedEventArgs e)
        {
            var webView = sender as WebView2;
            if (webView != null)
            {
                var tab = TabGroupManager.TabGroups.SelectMany(g => g.TabsInGroup).FirstOrDefault(t => t.WebViewInstance == webView);
                if (tab != null && SelectedTabItem == tab)
                {
                    AddressBar.Text = webView.Source.ToString(); // Update address bar if it's the selected tab
                }
            }
        }

        // Event handler for WebView2 CoreWebView2InitializationCompleted event
        private async void WebView_CoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            var webView = sender as WebView2;
            if (webView != null && webView.CoreWebView2 != null)
            {
                // Configure WebView2 settings
                webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = true;
                webView.CoreWebView2.Settings.AreDevToolsEnabled = false;
                webView.CoreWebView2.Settings.IsStatusBarEnabled = false;

                // Apply ad blocker filter if enabled
                if (IsAdBlockerEnabled)
                {
                    webView.CoreWebView2.SetWebResourceContextFilter(
                        CoreWebView2WebResourceContext.Image, CoreWebView2WebResourceContext.Script,
                        CoreWebView2WebResourceContext.Stylesheet, CoreWebView2WebResourceContext.Media,
                        CoreWebView2WebResourceContext.Font);
                }

                // Add scripts to execute on document creation for enabled extensions
                foreach (var extension in ExtensionManager.Extensions)
                {
                    if (extension.IsEnabled)
                    {
                        string scriptContent = extension.LoadScriptContent();
                        if (!string.IsNullOrEmpty(scriptContent))
                        {
                            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(scriptContent);
                        }
                    }
                }
            }
        }

        // Event handler for TabControl SelectionChanged event (for grouped tabs)
        private void BrowserTabControl_SelectionChanged_Grouped(object sender, SelectionChangedEventArgs e)
        {
            if (BrowserTabs.SelectedItem is TabItemData selectedTab)
            {
                SelectedTabItem = selectedTab; // Update SelectedTabItem
                AddressBar.Text = selectedTab.Url; // Update address bar
                UpdateNavigationButtons(); // Update navigation button states
            }
            else
            {
                AddressBar.Text = "";
                UpdateNavigationButtons();
            }
        }

        // Updates the visibility and state of browser controls
        private void UpdateBrowserControls()
        {
            IsFindBarVisible = false; // Hide find bar
            FindTextBox.Text = ""; // Clear find text
            FindResultsTextBlock.Text = ""; // Clear find results
            SelectedTabItem?.WebViewInstance?.CoreWebView2?.StopFindInPage(); // Stop any active find operation

            UpdateNavigationButtons(); // Update navigation buttons
        }

        // Updates the enabled/disabled state of back and forward buttons
        private void UpdateNavigationButtons()
        {
            GoBackButton.IsEnabled = SelectedTabItem?.WebViewInstance?.CanGoBack ?? false;
            GoForwardButton.IsEnabled = SelectedTabItem?.WebViewInstance?.CanGoForward ?? false;
        }

        // Event handler for Find button click (toggles find bar visibility)
        private void FindButton_Click(object sender, RoutedEventArgs e)
        {
            IsFindBarVisible = true;
            FindTextBox.Focus(); // Focus the find text box
        }

        // Event handler for Close Find Bar button click
        private void CloseFindBarButton_Click(object sender, RoutedEventArgs e)
        {
            IsFindBarVisible = false;
            FindTextBox.Text = "";
            FindResultsTextBlock.Text = "";
            SelectedTabItem?.WebViewInstance?.CoreWebView2?.StopFindInPage(); // Stop find operation
        }

        // Event handler for FindTextBox TextChanged event
        private void FindTextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            FindInPage(FindTextBox.Text); // Perform search as text changes
        }

        // Performs find in page operation
        private void FindInPage(string searchText)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null)
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    SelectedTabItem.WebViewInstance.CoreWebView2.FindInPage(
                        searchText,
                        CoreWebView2FindInPageKind.None, // Start a new search
                        false, // Do not case-sensitive
                        (sender, args) =>
                        {
                            FindResultsTextBlock.Text = $"{args.ActiveMatch}/{args.Matches}"; // Update results text
                        }
                    );
                }
                else
                {
                    SelectedTabItem.WebViewInstance.CoreWebView2.StopFindInPage(); // Stop find if search text is empty
                    FindResultsTextBlock.Text = "";
                }
            }
        }

        // Event handler for Find Next button click
        private void FindNextButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null && !string.IsNullOrEmpty(FindTextBox.Text))
            {
                SelectedTabItem.WebViewInstance.CoreWebView2.FindInPage(
                    FindTextBox.Text,
                    CoreWebView2FindInPageKind.Next, // Find next occurrence
                    false,
                    (sender, args) =>
                    {
                        FindResultsTextBlock.Text = $"{args.ActiveMatch}/{args.Matches}";
                    }
                );
            }
        }

        // Event handler for Find Previous button click
        private void FindPreviousButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null && !string.IsNullOrEmpty(FindTextBox.Text))
            {
                SelectedTabItem.WebViewInstance.CoreWebView2.FindInPage(
                    FindTextBox.Text,
                    CoreWebView2FindInPageKind.Previous, // Find previous occurrence
                    false,
                    (sender, args) =>
                    {
                        FindResultsTextBlock.Text = $"{args.ActiveMatch}/{args.Matches}";
                    }
                );
            }
        }

        // Event handler for History button click (opens HistoryWindow)
        private void HistoryButton_Click(object sender, RoutedEventArgs e)
        {
            // Ensure HistoryWindow exists in your project and is accessible
            var historyWindow = new HistoryWindow();
            historyWindow.ShowDialog();
        }

        // Event handler for Bookmarks button click (opens BookmarksWindow)
        private void BookmarksButton_Click(object sender, RoutedEventArgs e)
        {
            // Ensure BookmarksWindow exists in your project and is accessible
            var bookmarksWindow = new BookmarksWindow();
            bookmarksWindow.ShowDialog();
        }

        // Event handler for Password Manager button click (opens PasswordManagerWindow)
        private void PasswordManagerButton_Click(object sender, RoutedEventArgs e)
        {
            // Ensure PasswordManagerWindow exists in your project and is accessible
            var passwordManagerWindow = new PasswordManagerWindow();
            passwordManagerWindow.ShowDialog();
        }

        // Event handler for Data Extraction button click (opens DataExtractionWindow)
        private void DataExtractionButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null)
            {
                // Ensure DataExtractionWindow exists in your project and is accessible
                var dataExtractionWindow = new DataExtractionWindow(SelectedTabItem.WebViewInstance.CoreWebView2);
                dataExtractionWindow.Show();
            }
            else
            {
                MessageBox.Show("No active tab to extract data from.", "Error", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }

        // Event handler for Settings button click (opens SettingsWindow)
        private void SettingsButton_Click(object sender, RoutedEventArgs e)
        {
            // Ensure SettingsWindow exists in your project and is accessible
            var settingsWindow = new SettingsWindow();
            settingsWindow.HomePage = _defaultHomePage;
            settingsWindow.IsAdBlockerEnabled = IsAdBlockerEnabled;
            settingsWindow.IsTabSuspensionEnabled = IsTabSuspensionEnabled;

            if (settingsWindow.ShowDialog() == true)
            {
                _defaultHomePage = settingsWindow.HomePage;
                IsAdBlockerEnabled = settingsWindow.IsAdBlockerEnabled;
                IsTabSuspensionEnabled = settingsWindow.IsTabSuspensionEnabled;
                SaveSettings(); // Save settings after dialog closes
            }
        }

        // Event handler for Picture-in-Picture (PIP) button click
        private void PipButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null && !string.IsNullOrEmpty(SelectedTabItem.Url))
            {
                string videoUrl = SelectedTabItem.Url;

                try
                {
                    // Ensure PipWindow exists in your project and is accessible
                    var pipWindow = new PipWindow(videoUrl, SelectedTabItem.WebViewInstance.CoreWebView2.Environment);
                    pipWindow.Show();
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error opening PIP window: {ex.Message}", "PIP Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
            else
            {
                MessageBox.Show("No valid URL to open in PIP.", "Error", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }

        // Event handler for WebView2 ContextMenuOpening event (can customize context menu)
        private void WebView_ContextMenuOpening(object sender, ContextMenuEventArgs e)
        {
            // You can add custom items to the context menu here if needed
        }

        // Event handler for Read Aloud button click (toggles text-to-speech)
        private async void ReadAloudButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null)
            {
                if (_isReadingAloud)
                {
                    _speechSynthesizer?.SpeakAsyncCancelAll(); // Stop current speech
                    _isReadingAloud = false;
                    ReadAloudButton.ToolTip = "Read Aloud"; // Change tooltip back
                }
                else
                {
                    try
                    {
                        // JavaScript to extract all visible text from the page
                        string extractTextScript = @"
                            (function() {
                                var bodyText = document.body.innerText;
                                return bodyText;
                            })();
                        ";
                        string pageTextJson = await SelectedTabItem.WebViewInstance.CoreWebView2.ExecuteScriptAsync(extractTextScript);
                        string pageText = JsonSerializer.Deserialize<string>(pageTextJson) ?? "";

                        if (!string.IsNullOrEmpty(pageText))
                        {
                            _speechSynthesizer?.SpeakAsync(pageText); // Start speaking
                            _isReadingAloud = true;
                            ReadAloudButton.ToolTip = "Stop Reading"; // Change tooltip
                        }
                        else
                        {
                            MessageBox.Show("Could not extract text from the page to read aloud.", "Read Aloud", MessageBoxButton.OK, MessageBoxImage.Information);
                        }
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"Error reading aloud: {ex.Message}", "Reading Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
        }

        // Event handler for Reader Mode button click (toggles simplified view)
        private async void ReaderModeButton_Click(object sender, RoutedEventArgs e)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null)
            {
                try
                {
                    if (SelectedTabItem.IsReaderMode)
                    {
                        // Exit reader mode: navigate back to original URL
                        if (!string.IsNullOrEmpty(SelectedTabItem.Url))
                        {
                            SelectedTabItem.WebViewInstance.Source = new Uri(SelectedTabItem.Url);
                        }
                        SelectedTabItem.IsReaderMode = false;
                        ReaderModeButton.ToolTip = "Reader Mode";
                    }
                    else
                    {
                        // CSS for reader mode styling
                        string readerModeCss = @"
                            body {
                                font-family: 'Georgia', serif;
                                line-height: 1.6;
                                max-width: 800px;
                                margin: 0 auto;
                                padding: 20px;
                                background-color: #f9f9f9;
                                color: #333;
                            }
                            p {
                                margin-bottom: 1em;
                            }
                            img {
                                max-width: 100%;
                                height: auto;
                                display: block;
                                margin: 1em auto;
                            }
                            h1, h2, h3, h4, h5, h6 {
                                font-family: 'Helvetica Neue', sans-serif;
                                color: #1a1a1a;
                                margin-top: 1.5em;
                                margin-bottom: 0.5em;
                            }
                            a {
                                color: #007bff;
                                text-decoration: none;
                            }
                            a:hover {
                                text-decoration: underline;
                            }
                            header, footer, nav, aside, .sidebar, .comments, .ads, .related-posts {
                                display: none !important;
                            }
                        ";

                        // JavaScript to inject CSS and remove irrelevant elements for reader mode
                        string readerModeScript = @"
                            (function() {
                                var style = document.createElement('style');
                                style.textContent = `" + readerModeCss.Replace("`", "\\`") + @"`;
                                document.head.appendChild(style);

                                var elementsToRemove = 'header, footer, nav, aside, .sidebar, .comments, .ads, .related-posts, script, style';
                                document.querySelectorAll(elementsToRemove).forEach(function(el) {
                                    el.parentNode.removeChild(el);
                                });

                                document.body.style.margin = '0 auto';
                                document.body.style.maxWidth = '800px';
                                document.body.style.padding = '20px';
                            })();
                        ";
                        await SelectedTabItem.WebViewInstance.CoreWebView2.ExecuteScriptAsync(readerModeScript);
                        SelectedTabItem.IsReaderMode = true;
                        ReaderModeButton.ToolTip = "Disable Reader Mode";
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error changing reader mode: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }

        // Event handler for Incognito button click (shows information message)
        private void IncognitoButton_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Incognito mode opens a new window where browsing activity is not saved in history or cookies after closing the window.", "Incognito Mode", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        // Event handler for Extension menu item click (toggles extension state)
        private void ExtensionMenuItem_Click(object sender, RoutedEventArgs e)
        {
            if (sender is MenuItem menuItem && menuItem.Tag is CustomExtension extension)
            {
                extension.IsEnabled = !extension.IsEnabled;
                ApplyExtension(extension); // Apply extension changes
            }
        }

        // Applies or unapplies an extension's script to the current WebView2
        private async void ApplyExtension(CustomExtension extension)
        {
            if (SelectedTabItem?.WebViewInstance?.CoreWebView2 != null)
            {
                string scriptContent = extension.LoadScriptContent();
                if (!string.IsNullOrEmpty(scriptContent))
                {
                    if (extension.IsEnabled)
                    {
                        await SelectedTabItem.WebViewInstance.CoreWebView2.ExecuteScriptAsync(scriptContent);
                    }
                    else
                    {
                        MessageBox.Show($"The extension '{extension.Name}' has been {(extension.IsEnabled ? "activated" : "deactivated")}. You may need to reload the page to see changes.", "Extensions", MessageBoxButton.OK, MessageBoxImage.Information);
                    }
                }
            }
        }

        // Event handler for Manage Extensions button click (opens ExtensionsWindow)
        private void ManageExtensionsButton_Click(object sender, RoutedEventArgs e)
        {
            // Ensure ExtensionsWindow exists in your project and is accessible
            var extensionsWindow = new ExtensionsWindow(ExtensionManager);
            extensionsWindow.ShowDialog();
        }

        // Event handler for WebView2 WebMessageReceived event (handles messages from injected scripts)
        private async void WebView_WebMessageReceived(object? sender, CoreWebView2WebMessageReceivedEventArgs e)
        {
            var webView = sender as WebView2;
            if (webView == null) return;

            string message = e.WebMessageAsJson; // Get the message as JSON

            try
            {
                using (JsonDocument doc = JsonDocument.Parse(message))
                {
                    if (doc.RootElement.TryGetProperty("type", out JsonElement typeElement))
                    {
                        string messageType = typeElement.GetString() ?? "";

                        switch (messageType)
                        {
                            case "extractedText":
                                if (doc.RootElement.TryGetProperty("text", out JsonElement textElement))
                                {
                                    string extractedText = textElement.GetString() ?? "";
                                    Console.WriteLine($"Extracted Text: {extractedText.Substring(0, Math.Min(extractedText.Length, 200))}...");

                                    var tab = TabGroupManager.TabGroups.SelectMany(g => g.TabsInGroup).FirstOrDefault(t => t.WebViewInstance == webView);
                                    if (tab != null)
                                    {
                                        tab.CapturedData.ExtractedText = extractedText; // Store extracted text in tab data
                                    }
                                }
                                break;
                            case "passwordDetected":
                                if (doc.RootElement.TryGetProperty("url", out JsonElement urlElement) &&
                                    doc.RootElement.TryGetProperty("username", out JsonElement usernameElement) &&
                                    doc.RootElement.TryGetProperty("password", out JsonElement passwordElement))
                                {
                                    string url = urlElement.GetString() ?? "";
                                    string username = usernameElement.GetString() ?? "";
                                    string password = passwordElement.GetString() ?? "";

                                    var result = MessageBox.Show($"Do you want to save the password for {username} on {url}?", "Save Password", MessageBoxButton.YesNo, MessageBoxImage.Question);
                                    if (result == MessageBoxResult.Yes)
                                    {
                                        PasswordManager.SavePassword(url, username, password); // Save password using PasswordManager
                                        MessageBox.Show("Password saved successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                                    }
                                }
                                break;
                        }
                    }
                }
            }
            catch (JsonException ex)
            {
                Console.WriteLine($"Error parsing WebView2 message as JSON: {ex.Message}");
                Console.WriteLine($"Message received from WebView2: {message}");
            }
        }

        // Event handler for WebView2 DownloadStarting event (handles file downloads)
        private void WebView_DownloadStarting(object? sender, CoreWebView2DownloadStartingEventArgs e)
        {
            e.Cancel = true; // Cancel default download behavior

            string suggestedFileName = Path.GetFileName(e.ResultFilePath); // Get suggested file name

            Microsoft.Win32.SaveFileDialog saveFileDialog = new Microsoft.Win32.SaveFileDialog();
            saveFileDialog.FileName = suggestedFileName;
            saveFileDialog.Title = "Save File";

            if (saveFileDialog.ShowDialog() == true)
            {
                e.ResultFilePath = saveFileDialog.FileName; // Set custom download path
                e.Cancel = false; // Allow download to proceed

                DownloadProgressBarVisibility = Visibility.Visible; // Show progress bar
                DownloadProgress = 0; // Reset progress

                // Update progress bar as bytes are received
                e.DownloadOperation.BytesReceivedChanged += (s, args) =>
                {
                    Dispatcher.Invoke(() =>
                    {
                        if (e.DownloadOperation.TotalBytesToReceive > 0)
                        {
                            DownloadProgress = (double)e.DownloadOperation.BytesReceived * 100 / e.DownloadOperation.TotalBytesToReceive;
                        }
                    });
                };

                // Handle download state changes (completed, interrupted)
                e.DownloadOperation.StateChanged += (s, args) =>
                {
                    Dispatcher.Invoke(() =>
                    {
                        switch (e.DownloadOperation.State)
                        {
                            case CoreWebView2DownloadState.Completed:
                                MessageBox.Show($"Download completed: {e.ResultFilePath}", "Download", MessageBoxButton.OK, MessageBoxImage.Information);
                                DownloadProgressBarVisibility = Visibility.Collapsed; // Hide progress bar
                                break;
                            case CoreWebView2DownloadState.Interrupted:
                                MessageBox.Show($"Download interrupted: {e.DownloadOperation.InterruptReason}", "Download Failed", MessageBoxButton.OK, MessageBoxImage.Error);
                                DownloadProgressBarVisibility = Visibility.Collapsed; // Hide progress bar
                                break;
                        }
                    });
                };
            }
            else
            {
                e.Cancel = true; // Cancel download if user doesn't select a path
            }
        }

        // Command for adding a new tab group
        public ICommand AddTabGroupCommand => new RelayCommand(_ => AddNewTabGroup());

        // Adds a new tab group
        private void AddNewTabGroup()
        {
            var newGroup = new TabGroup($"Group {TabGroupManager.TabGroups.Count + 1}");
            TabGroupManager.AddGroup(newGroup); // Add new group to manager
            TabGroupManager.SelectedTabGroup = newGroup; // Select the new group
            AddNewTab(_defaultHomePage); // Add a new tab to the new group
            BrowserTabs.ItemsSource = newGroup.TabsInGroup; // Update TabControl's ItemsSource
        }

        // Command for selecting a tab group
        public ICommand SelectTabGroupCommand => new RelayCommand(parameter =>
        {
            if (parameter is TabGroup selectedGroup)
            {
                TabGroupManager.SelectedTabGroup = selectedGroup; // Set selected group
                BrowserTabs.ItemsSource = selectedGroup.TabsInGroup; // Update TabControl's ItemsSource
                SelectedTabItem = selectedGroup.TabsInGroup.FirstOrDefault(); // Select the first tab in the group
            }
        });

        // Event handler for MainWindow SourceInitialized event (for custom window dragging)
        private void MainWindow_SourceInitialized(object sender, EventArgs e)
        {
            HwndSource? source = PresentationSource.FromVisual(this) as HwndSource;
            if (source != null)
            {
                source.AddHook(WndProc); // Add hook for custom window procedure
            }
        }

        // Custom window procedure for handling non-client area messages (e.g., dragging)
        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            switch (msg)
            {
                case WM_NCLBUTTONDOWN:
                    if (wParam.ToInt32() == HT_CAPTION)
                    {
                        handled = true; // Handle caption area click for dragging
                    }
                    break;
            }
            return IntPtr.Zero;
        }

        // Event handler for Gemini button click (captures page data and opens GeminiDataViewerWindow)
        private async void GeminiButton_Click(object sender, RoutedEventArgs e)
        {
            var capturedDataList = new ObservableCollection<CapturedPageData>();

            if (SelectedTabItem != null)
            {
                // Ensure WebView2 Core is initialized
                if (SelectedTabItem.WebViewInstance.CoreWebView2 == null)
                {
                    await SelectedTabItem.WebViewInstance.EnsureCoreWebView2Async(null);
                }

                try
                {
                    // Extract text content from the page
                    string extractedText = await GetPageText(SelectedTabItem.WebViewInstance.CoreWebView2);
                    SelectedTabItem.CapturedData.ExtractedText = extractedText;

                    // Capture screenshot of the page
                    string screenshotBase64 = await CaptureScreenshotAsync(SelectedTabItem.WebViewInstance);
                    SelectedTabItem.CapturedData.ScreenshotBase64 = screenshotBase64;

                    // Convert favicon to Base64 if available
                    if (string.IsNullOrEmpty(SelectedTabItem.CapturedData.FaviconBase64) && SelectedTabItem.Favicon != null)
                    {
                        SelectedTabItem.CapturedData.FaviconBase64 = ConvertBitmapImageToBase64(SelectedTabItem.Favicon);
                    }

                    // Populate captured data with URL and title
                    SelectedTabItem.CapturedData.Url = SelectedTabItem.Url;
                    SelectedTabItem.CapturedData.Title = SelectedTabItem.Title;

                    capturedDataList.Add(SelectedTabItem.CapturedData); // Add captured data to the list
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error capturing page data for Gemini: {ex.Message}", "Capture Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }
            }
            else
            {
                MessageBox.Show("No active web tab to send to Gemini.", "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            // Open GeminiDataViewerWindow to display captured data and get user question
            var geminiViewerWindow = new GeminiDataViewerWindow(capturedDataList);
            geminiViewerWindow.Owner = this; // Set owner to main window

            if (geminiViewerWindow.ShowDialog() == true)
            {
                string userQuestion = geminiViewerWindow.UserQuestion; // Get user's question

                MessageBox.Show($"Data sent to Gemini with question: '{userQuestion}'", "Gemini", MessageBoxButton.OK, MessageBoxImage.Information);
                IsGeminiModeActive = true; // Activate Gemini mode
            }
            else
            {
                MessageBox.Show("Sending to Gemini canceled.", "Gemini", MessageBoxButton.OK, MessageBoxImage.Information);
                IsGeminiModeActive = false; // Deactivate Gemini mode
            }
        }

        // Extracts text content from a WebView2 page
        private async Task<string> GetPageText(CoreWebView2 webView)
        {
            if (webView == null) return string.Empty;

            try
            {
                // JavaScript to extract text from common content elements or body
                string script = @"
                    (function() {
                        var selectors = ['article', 'main', 'body'];
                        for (var i = 0; i < selectors.length; i++) {
                            var element = document.querySelector(selectors[i]);
                            if (element && element.innerText) {
                                return element.innerText;
                            }
                        }
                        return document.body.innerText;
                    })();
                ";
                string pageTextJson = await webView.ExecuteScriptAsync(script);
                return JsonSerializer.Deserialize<string>(pageTextJson) ?? string.Empty;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error extracting text from page: {ex.Message}");
                return string.Empty;
            }
        }

        // Captures a screenshot of the WebView2 content
        private async Task<string> CaptureScreenshotAsync(WebView2 webView)
        {
            if (webView.CoreWebView2 == null)
            {
                await webView.EnsureCoreWebView2Async(null);
            }

            try
            {
                // Get content size using JavaScript
                var contentSizeJson = await webView.CoreWebView2.ExecuteScriptAsync(
                    "(function() { " +
                    "  var body = document.body, html = document.documentElement;" +
                    "  var height = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );" +
                    "  var width = Math.max( body.scrollWidth, body.offsetWidth, html.clientWidth, html.scrollWidth, html.offsetWidth );" +
                    "  return { width: width, height: height };" +
                    "})()"
                );

                using (JsonDocument doc = JsonDocument.Parse(contentSizeJson))
                {
                    int contentWidth = doc.RootElement.GetProperty("width").GetInt32();
                    int contentHeight = doc.RootElement.GetProperty("height").GetInt32();

                    // Limit dimensions to avoid excessive memory usage
                    const int MAX_DIMENSION = 8000;
                    contentWidth = Math.Min(contentWidth, MAX_DIMENSION);
                    contentHeight = Math.Min(contentHeight, MAX_DIMENSION);

                    // Store original WebView dimensions
                    double originalWidth = webView.Width;
                    double originalHeight = webView.Height;

                    // Temporarily resize WebView to content size for full screenshot
                    Dispatcher.Invoke(() =>
                    {
                        webView.Width = contentWidth;
                        webView.Height = contentHeight;
                        webView.Measure(new Size(contentWidth, contentHeight));
                        webView.Arrange(new Rect(0, 0, contentWidth, contentHeight));
                    });

                    await Task.Delay(50); // Small delay to allow rendering

                    using (MemoryStream stream = new MemoryStream())
                    {
                        await webView.CoreWebView2.CapturePreviewAsync(CoreWebView2CapturePreviewImageFormat.Png, stream); // Capture preview

                        // Restore original WebView dimensions
                        Dispatcher.Invoke(() =>
                        {
                            webView.Width = originalWidth;
                            webView.Height = originalHeight;
                            webView.Measure(new Size(originalWidth, originalHeight));
                            webView.Arrange(new Rect(0, 0, originalWidth, originalHeight));
                        });

                        byte[] imageBytes = stream.ToArray();
                        return "data:image/png;base64," + Convert.ToBase64String(imageBytes); // Return Base64 string
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error capturing screenshot: {ex.Message}");
                return string.Empty;
            }
        }

        // Converts a BitmapImage to a Base64 string
        private string ConvertBitmapImageToBase64(BitmapImage bitmapImage)
        {
            if (bitmapImage == null) return string.Empty;

            try
            {
                MemoryStream stream = new MemoryStream();
                PngBitmapEncoder encoder = new PngBitmapEncoder();
                encoder.Frames.Add(BitmapFrame.Create(bitmapImage));
                encoder.Save(stream);
                byte[] bytes = stream.ToArray();
                return Convert.ToBase64String(bytes);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error converting BitmapImage to Base64: {ex.Message}");
                return string.Empty;
            }
        }

        // Saves a Base64 image string as a PNG file
        private void SaveBase64ImageAsPng(string base64String, string filePath)
        {
            if (string.IsNullOrEmpty(base64String)) return;

            try
            {
                byte[] imageBytes = Convert.FromBase64String(base64String.Replace("data:image/png;base64,", ""));
                File.WriteAllBytes(filePath, imageBytes);
                MessageBox.Show($"Screenshot saved to: {filePath}", "Screenshot Saved", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error saving screenshot: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
    }
}
